### PR TITLE
Hotfix #15 remove redeclared fields

### PR DESCRIPTION
**Pull request by zonky2**
Hotfix #15 remove re-declaration fields

### CODE REVIEW

**Comment by discordier** [comment]
You forgot to remove the language strings.
https://github.com/MetaModels/filter_tags/blob/70af692d56d9cc2caf94adb0c7d711eb5584c0a1/contao/languages/en/tl_metamodel_filtersetting.php#L27

**Comment by zonky2** [comment]
done

**Comment by zonky2** [comment]
> Some Masters speculate that it is precisely because of their trust in the Force rather than their eyes that they fight so fluently with Lightsabers.

;-)

**Comment by zonky2** [comment]
>Looks good to me now.

open fire!

**Comment by discordier** [comment]
What do you mean? According to git, @stefanheimes has merged it into the hotfix branch already on Sep 20 with commit fa9f57aa00b195cc7ed23b8699b0afa77de410ce.

Closing therefore.

**Pull request closed without merging**
